# Generated by Django 3.2.4 on 2021-07-01 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField(null=True)),
                ('username', models.CharField(max_length=64, verbose_name='username')),
                ('avatar', models.CharField(default='', max_length=64, verbose_name='profile_pic')),
                ('content', models.TextField(blank=True, max_length=5000, verbose_name='content')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='publication_date')),
                ('tid', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_tw', to='landing.twitter', verbose_name='comment_content')),
            ],
        ),
    ]
