# Generated by Django 3.2.4 on 2021-07-04 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='avatar',
            field=models.CharField(default='', max_length=64, verbose_name='profile_picture'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='tid',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_tw', to='landing.twitter', verbose_name='id'),
        ),
    ]
