# Generated by Django 3.2.4 on 2021-07-04 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20210704_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitter',
            old_name='comment',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='twitter',
            old_name='fav',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='twitter',
            old_name='zhuan',
            new_name='reposts',
        ),
    ]
