# Generated by Django 3.2.4 on 2021-06-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagereport',
            name='username',
            field=models.CharField(default='{{request.post.author}}', editable=False, max_length=7),
        ),
        migrations.AddField(
            model_name='userreport',
            name='username',
            field=models.CharField(default='{{request.post.author}}', editable=False, max_length=7),
        ),
    ]
