# Generated by Django 3.2.4 on 2021-06-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20210629_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagereport',
            name='username',
            field=models.CharField(default='{{request.post.author}}', max_length=7),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='username',
            field=models.CharField(default='{{request.post.author}}', max_length=7),
        ),
    ]
