# Generated by Django 3.2.4 on 2021-07-01 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20210630_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreport',
            name='username',
            field=models.CharField(default='{{request.post.author}}', max_length=200, null=True),
        ),
    ]
