# Generated by Django 3.2.4 on 2021-07-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_alter_messagereport_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagereport',
            name='content',
            field=models.CharField(default='{{request.post.content}}', max_length=500, null=True),
        ),
    ]
