# Generated by Django 3.2.2 on 2021-06-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Twitter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField(null=True)),
                ('username', models.CharField(max_length=64, verbose_name='username')),
                ('fav', models.IntegerField(null=True)),
                ('comment', models.IntegerField(null=True)),
                ('zhuan', models.IntegerField(null=True)),
                ('content', models.TextField(blank=True, max_length=5000, verbose_name='content')),
                ('pic', models.ImageField(null=True, upload_to='static/images/', verbose_name='attached_image')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='publication_date')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
            },
        ),
    ]
