# Generated by Django 3.2.2 on 2021-06-30 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210701_0111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Twitter',
        ),
    ]
