# Generated by Django 3.2.4 on 2021-07-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('time_stamp', models.DateTimeField(auto_now_add=True, verbose_name='publication_date')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender_id', models.IntegerField(null=True)),
                ('receiver_id', models.IntegerField(null=True)),
                ('content', models.TextField(blank=True, max_length=5000, verbose_name='content')),
            ],
        ),
    ]
